DROP DATABASE IF EXISTS webchat;
DROP USER IF EXISTS `webchatadmin`@`%`;
CREATE DATABASE IF NOT EXISTS webchat CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `webchatadmin`@`%` IDENTIFIED WITH mysql_native_password BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `webchat`.* TO `webchatadmin`@`%`;